# Generated by Django 6.0.3 on 2026-03-10

from django.db import migrations, models


def migrate_legacy_roles(apps, schema_editor):
    UserProfile = apps.get_model("auth_custom", "UserProfile")
    mapping = {
        "architect": "owner",
        "director": "owner",
        "project_manager": "owner",
        "analyst": "guest",
        "viewer": "guest",
    }
    allowed = {"admin", "owner", "editor", "guest"}
    for profile in UserProfile.objects.all():
        role = (profile.role or "").strip().lower()
        if role in mapping:
            profile.legacy_role = role
            profile.role = mapping[role]
        elif role not in allowed:
            profile.role = "guest"
        profile.save(update_fields=["role", "legacy_role", "updated_at"])


def rollback_legacy_roles(apps, schema_editor):
    UserProfile = apps.get_model("auth_custom", "UserProfile")
    reverse_mapping = {
        "owner": "architect",
        "guest": "viewer",
    }
    allowed_legacy = {"architect", "director", "project_manager", "analyst", "viewer"}
    for profile in UserProfile.objects.all():
        legacy_role = (profile.legacy_role or "").strip().lower()
        if legacy_role in allowed_legacy:
            profile.role = legacy_role
        else:
            profile.role = reverse_mapping.get(profile.role, "viewer")
        profile.save(update_fields=["role", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0002_refreshtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="legacy_role",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.RunPython(migrate_legacy_roles, rollback_legacy_roles),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                    ("editor", "Editor"),
                    ("guest", "Guest"),
                ],
                default="guest",
                max_length=32,
            ),
        ),
    ]
