# Generated by Django 6.0.3 on 2026-04-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0006_userprofile_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_setup_2fa",
            field=models.BooleanField(default=False),
        ),
    ]
