# Generated by Django 6.0.3 on 2026-03-10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technologies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technologyenterprisereadiness",
            name="technological_readiness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="technologyenterprisereadiness",
            name="organizational_readiness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
    ]
