# Generated by Django 6.0.3 on 2026-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technologies", "0003_technologyproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technologyproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("postponed", "Postponed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
