# Generated by Django 6.0.3 on 2026-04-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technologies", "0004_proposal_notifications"),
        ("technologies", "0005_technologyproposal_hidden_from_creator_history"),
    ]

    operations = []
